project_id = "kxombsamuzjwegdhwdve"

[functions.phala-chat]
verify_jwt = false

[functions.ipfs-operations]
verify_jwt = false

[functions.process-journal-memory]
verify_jwt = false

[functions.fulfill-entry]
verify_jwt = false

[functions.aes-crypto]
verify_jwt = false
