// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxombsamuzjwegdhwdve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4b21ic2FtdXpqd2VnZGh3ZHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTcwOTMsImV4cCI6MjA3MjU3MzA5M30.cE4_12M5KgaSxx3owZLovsLUycI2ZXR41UKM4-fhAaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});